### ISSUE TITLE
CRUD-editor has incorrect UI in IE11

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-crudeditor#121]
If CRUD-editor is opened in IE, Search Result and Search fields are not displayed. 

![90](https://user-images.githubusercontent.com/25082017/33888601-9d054b22-df5e-11e7-9731-60a165b30079.png)

**Comment by kvolkovich-sc** [comment]
Duplicate of https://github.com/OpusCapita/react-crudeditor/issues/13
