### ISSUE TITLE
Reset action doesn't work

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-crudeditor#125]
1. Open CRUD-editor;
2. input values in searching fields;
3. click on "Reset" link.
Result: searching fields are not cleared (except "Parent Contract" and "Status Id").
Expected result:  searching fields are cleared.

**Comment by estambakio-sc** [comment]
@nstoliar-sc  
I don't reproduce this bug on current master branch: 

https://opuscapita.github.io/react-crudeditor/branches/master/?currentComponentName=ContractEditor&maxContainerWidth=100%25&showSidebar=false

Please check it and confirm weither this behavior is fixed or not.
