### ISSUE TITLE
Wrong pagination is displayed if all elements of search result  should be displayed on one page

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-crudeditor#127]
1. Open CRUD-editor;
2. select "All" value in "Result per page" field;
3. make search;
4. pay attention on pagination. 
Result: navigation arrows are not hidden; `-1` value is displayed in "Result per page" field. 

![92](https://user-images.githubusercontent.com/25082017/33895932-a6a9f3ee-df72-11e7-8f69-d507a3204a9c.png)

**Comment by estambakio-sc** [comment]
Fixed in #130
