### ISSUE TITLE
IE11 search view issue

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/react-crudeditor#13]
Up to date branch: [link](https://opuscapita.github.io/react-crudeditor/branches/master/?currentComponentId=%40opuscapita%2Freact-crudeditor%2F0.0.30%2FContractEditor)

Starting showroom build: **yarn start-showroom**

Search view collapses vertically in IE11. Other views are fine.

**Comment by estambakio-sc** [comment]
Current known issues: 

1. Button dropdowns hide under bottom scroll bar. How to fix: conditionally apply `dropup = true` to such dropdowns (calculate heights).
1. Crud-in-crud: inner crud collapses vertically in IE 11. How to fix: N/A

**Comment by estambakio-sc** [comment]
[Demo website for QA](https://opuscapita.github.io/react-crudeditor/branches/issue-13-UI-fixes/?currentComponentName=ContractEditor&maxContainerWidth=100%25&showSidebar=false)

**Comment by nstoliar-sc** [comment]
Tested. UI of Contract CRUD-editor is displayed in IE. Please, merge with master branch. Spent 4 hours. 
Issues https://github.com/OpusCapita/react-crudeditor/issues/251 and https://github.com/OpusCapita/react-crudeditor/issues/252 were created.
