### ISSUE TITLE
Better i18n for field errors

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/react-crudeditor#134]
TODO: handle i18n for field errors. 

i18n key pattern: `model.field.FIELD_NAME.error.ERROR_ID`, where 

`FIELD_NAME` is `field.name` and 
`ERROR_ID` is `id` in the error object: 

```
{
 code: ...,
 id: ...,
 message: ...
}
```

Expected behavior: return i18n string; if i18n returned the key itself (no translation found) -> show `message`, if no `message` specified -> show `id`.

**Comment by amourzenkov-sc** [comment]
Documentation in README must reflect the changes in error format

**Comment by estambakio-sc** [comment]
Added this to documentation: https://github.com/OpusCapita/react-crudeditor/commit/4c07d189386bbc6b29724e698f66f284470a965b
