### ISSUE TITLE
Implement possibility to alter built-in crud buttons using custom operations

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/react-crudeditor#150]

**Comment by estambakio-sc** [comment]
Implemented in `issue-150` branch: 

for each ui view there can be `standardOperation` object of the following shape: 

```
standardOperations: {
        'delete': { // id/name of a standard operation; will be exported as a constant from crud library
          hideIcon: false,
          icon: '', // default value: crud's default icon for this operation, or none
          hidden: false,
          disabled: false
        }
      }
```

Everything is optional; crud behavior is the default one for not specified options.

`hideIcon` and `icon` work only on Search view; have no effect on Edit/Show/Create views.

`standardOperations` are completely separate from `customOperations` defined in the model. If one needs to mimic a `Delete` button with a random handler he'd have to set `delete.hidden = true` for the corresponding view and create a customOperation for this purpose.

## TBD

Should we allow altering titles for standard operations buttons (delete, view, edit, search, save etc.) ? If yes, what the API should look like? 

Options: 
1. Following the current custom operations naming convention we can define a title key as `standardOperations.edit.name='edit'` and check for model i18n messages by key `model.label.edit` (pattern `model.label.OPERATION_NAME`). This will be consistent with current model translations behavior. If key is not found in translations - crud can use the standard one.
 
2. Just define a `title` prop with plain text. This is **not** consistent with current behavior of custom operations and field/tab/section labels i18n quering.

**Comment by estambakio-sc** [comment]
I have a proposal about allowing repositioning of instance-related buttons (**standard** ones, like `edit` or `delete`, **custom operations** in model and **external operations** defined via props).

These three groups of buttons are linked to particular instance and are displayed together. 

The goal is to **give an ability to define a custom layout** for these buttons. Flexible one and easy to use.

**For the user-end side** I propose the following API: 

```

// this function should be placed in model.ui.VIEW_NAME
//
// only instance-related buttons layout is handled here;
// all other editor buttons stay where they belong
//
// if layout is not specified - the default layout is used
// edit/show/create views are TBD - allow dropdowns or inline only, 
// allow inline repositioning or not, etc.

const instanceButtonsLayout = ({
  // 'standard' is an object of the following pattern: 
  // {
  //   'edit': {
  //     name: 'edit', // standard button name
  //     type: 'standard'
  //   },
  //   ...
  // }
  //
  //  PARAMS RECEIVED BY FUNCTION
  //
  standard, // built-in crud editor buttons

  // 'custom' and 'external' are arrays of similar objects
  custom, // operations defined by model.customOperations
  external // operations passed to editor via props
}) => 
  // despite the order, buttons are displayed based on permissions
  // in the following layout if 'edit' is permitted -> 
  // button 'edit' will be shown, button 'show' won't be displayed.
  // permissions are handled internally by crud editor
  // 
  // if mentioned button does not exist among available buttons -> 
  // it's simply not displayed. so, if there is a typo in layout -> 
  // there won't be a button. 
  //
  // for 'standard' buttons it's safe to mention maximum amount of buttons
  // and don't care about permissions the current user has
  // 
  //  THE LAYOUT ITSELF
  //
[
  standard['edit'], // a single object will become a regular button
  standard['show'], // either 'edit' or 'show' is displayed based on permissions system; just mention both
  [...custom], // an array will become a dropdown
  external[0], // a single button...
  [...external.slice(1)], // ...and adjusted dropdown
  standard['delete']
]
```

If this proposal receives positive feedback, I could provide internal implementation details I have in mind.

**Comment by estambakio-sc** [comment]
Comment by @dzhitomirsky-sc : no need to mix `standard` and `custom` buttons. This is enough to define layout in-place [where you define custom operations](https://github.com/OpusCapita/react-crudeditor/blob/master/src/demo/models/contracts/index.js#L418), and place `custom` buttons either before or after `standard` ones.

**Comment by estambakio-sc** [comment]
[Demo for QA](https://opuscapita.github.io/react-crudeditor/branches/issue-150(slash)sortable-operations/?currentComponentName=ContractEditor&maxContainerWidth=100%25&showSidebar=false)

**Comment by nstoliar-sc** [comment]
Tested in Chrome, FF and IE. Buttons are displayed correctly. Please, merge with master branch. Spent 0.5 hour.
