### ISSUE TITLE
Model Definition is not checked for validity when react-crudeditor package is used

### ISSUE THREAD

**Issue by amourzenkov-sc** [OpusCapita/react-crudeditor#199]
For example, absence of unique fields does not throw any warnings to console.

[PropTypes.checkPropTypes not called in production](https://github.com/facebook/prop-types/blob/01634d92e4e4cb5ffaf7de96ea8cb5da9b65e4f0/checkPropTypes.js#L29) is the reason.

**Comment by estambakio-sc** [comment]
Fixed in https://github.com/OpusCapita/react-crudeditor/commit/6c38f43dfd80fbd5c3248f4d50b889316306a010
