### ISSUE TITLE
App broken in IE11

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/react-crudeditor#2]
Application doesn't work in IE11 because it has problems with hot-loader.

Also `findIndex` method unsupported in IE. It should be fixed.
https://github.com/OpusCapita/react-crudeditor/blob/98f5bf914079e6fb709d8e8ac95e2de5b4ebd10d/src/crudeditor-lib/views/search/reducer.js#L80

**Comment by amourzenkov-sc** [comment]
Fixed
