### ISSUE TITLE
Date input field values are not fully visible when using Firefox

### ISSUE THREAD

**Issue by jarkinn** [OpusCapita/react-crudeditor#238]
With Firefox browser the crud editor date input field (like Valid From, Valid To) values are not fully visible:

![kuva](https://user-images.githubusercontent.com/29628663/35807366-355bbec2-0a8b-11e8-8cec-0cea5da095db.png)

With Chrome the values are shown correctly.

**Comment by estambakio-sc** [comment]
@jarkinn is it still a thing? I can't reproduce it. Please check again https://opuscapita.github.io/react-crudeditor/branches/master/?currentComponentName=ContractEditor&maxContainerWidth=100%25&showSidebar=false

**Comment by jarkinn** [comment]
Not reproducible anymore.
