### ISSUE TITLE
Firefox: CRUD editor's search button is not visible without scrolling

### ISSUE THREAD

**Issue by jarkinn** [OpusCapita/react-crudeditor#241]
Steps to reproduce:
- Open crud editor with Firefox
- Create so many items that the vertical scroll becomes visible to the editor
- Try to use crud editor's search

Expected behaviour:
- Crud editor's search button is directly visible to the user without need to find it.

Actual behaviour:
- User needs to scroll to the bottom of the screen to find the Search button.

Other information:
- Works as exepected with Chrome

**Comment by estambakio-sc** [comment]
@jarkinn do you reproduce it currently? [Please open this link in Firefox](https://opuscapita.github.io/react-crudeditor/branches/master/?currentComponentName=ContractEditor&maxContainerWidth=100%25&showSidebar=false) and let me know.

**Comment by estambakio-sc** [comment]
@jarkinn yes, please close it if it is irrelevant. 

I believe it was fixed in https://github.com/OpusCapita/react-crudeditor/commit/87e4b70e2984ea9b709d83cc3d77337c31071385

**Comment by jarkinn** [comment]
Issue is not reproducible.
