### ISSUE TITLE
Add DateRangeInput for Date fields on search form

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/react-crudeditor#25]

**Comment by amourzenkov-sc** [comment]
Allow ranges in Create/Edit/Show View
![image](https://user-images.githubusercontent.com/24649844/33210306-b10e3cf6-d12a-11e7-8400-9f368f089e14.png)

**Comment by amourzenkov-sc** [comment]
Also allow ranges in Create/Edit/Show View.
![image](https://user-images.githubusercontent.com/24649844/33210359-ec03a526-d12a-11e7-8cc6-ea3003beacb3.png)
