### ISSUE TITLE
Extend Page Navigation bar with manual page input

### ISSUE THREAD

**Issue by dsanko-sc** [OpusCapita/react-crudeditor#262]
# Todo
Input for page and button with text 'Go' (in English) should be added to the right of current page navigation.
It will look like this:
![pagination4](https://user-images.githubusercontent.com/25082620/38082082-489cb39c-334e-11e8-942a-cb873c7f2c9d.png)
Input behaviour:
1. Action: We enter number in range from '1' to max page number then press key 'Enter' on keyboard or button 'Go'
Result: Current page is entered value, input is clear
2. Action: We enter number less than '1' then press key 'Enter' on keyboard or button 'Go'
Result: Current page is not changed, input is clear
3. Action: We enter number more then max page number then press key 'Enter' on keyboard or button 'Go'
Result: Current page is max page number, input is clear
4. Action: We enter value which contains non-numeric symbols then press key 'Enter' on keyboard or button 'Go'
Result: Current page is not changed, input is clear

**Comment by asergeev-sc** [comment]
Tes it [here](https://opuscapita.github.io/react-crudeditor/branches/issue-262(slash)pagination-input)

**Comment by nstoliar-sc** [comment]
Tested. Pages are changed correctly using manual page input or clicking on appropriate page number or 'previous'/'next' arrow. Please, merge with master branch. Spent 1 hour.

**Comment by dsanko-sc** [comment]
Please, release it.
