### ISSUE TITLE
Save operation is not possible when failed validation of a field from inactive tab

### ISSUE THREAD

**Issue by amourzenkov-sc** [OpusCapita/react-crudeditor#269]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01
Original Estimation | 8h
Remaining Estimation | 0h

The situation arises when

1. A new field constraint is added effecting existing server-side DB instances.  Loading such an instance for editing does not allow saving changes made in a tab if no-longer-valid field is located in another tab.  Error massage is not informative in this case either.

2. Custom instance-validator compares fields from different tabs and does not allow their consecutive changes (only atomic changes to the fields are allowed).

**Comment by nstoliar-sc** [comment]
Tested for FF, IE and Chrome. Error message appears correctly and it is possible to expand this message if it has additional information. If user deletes several items and deleting of some item gives error, error message for deleting appropriate item appears while rest items are deleted correctly. Spent 2 hours.

Note: It might be implemented some improvements for usability. Current time of displaying of error message might be too short for reading of message with long text. It is might hold back displaying message, if user sends a cursor of mouse on this message, and expand additional information by clicking on it. After removing the mouse from message, it could be hidden after some time.

**Comment by nstoliar-sc** [comment]
Tested for FF, IE, Chrome. If user clicks on message for expanding additional information, message is displayed on time locating of cursor on this message. Please, merge with master branch. Spent 0,5 hours.
