### ISSUE TITLE
Add possibility to disable any action on search list in CRUD editor

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/react-crudeditor#273]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01
Original Estimation | 8h
Remaining Estimation | 0h

**Comment by estambakio-sc** [comment]
TODO: allow functions in `permissions` configuration.

Current state: crud permissions are defined in modelDefinition as boolean values.

```
permissions: {
    crudOperations: {
      create: true,
      edit: true,
      delete: true,
      view: true
    }
  }
```

Goal: crud permissions can be defined as boolean or functions:
```
permissions: {
    crudOperations: {
      create: true,
      edit: ({ instance }) => <boolean>,
      delete: true,
      view: true
    }
  },
```

In case of functions there will be 2 types of calls: 
- without arguments `crudOperations.edit()` to get crud-wide permission
- with an object containing `instance` to get instance-specific permission `crudOperations.edit({ instance })`

Example of such function: 
```
edit: arg => arg ? arg.instance.canBeEdited : true
```

**Comment by estambakio-sc** [comment]
`ui.VIEW_NAME.standardOperations` will be removed, because it duplicates new permissions functionality in current application (disabling `Delete` based on instance).

**Comment by estambakio-sc** [comment]
[Demo link](https://opuscapita.github.io/react-crudeditor/branches/issue-273/?currentComponentName=ContractEditor&maxContainerWidth=100%25&showSidebar=false)

**Comment by nstoliar-sc** [comment]
Tested. Navigation by instances in CRUD-editor is make correctly. Buttons of instances is displayed according permissions. Please, merge with master branch. Spent 1 hour.
