### ISSUE TITLE
Conform converter's format/parse arguments to README

### ISSUE THREAD

**Issue by amourzenkov-sc** [OpusCapita/react-crudeditor#277]
Meta-Info | Value
-- | --
ExtProjectId | JCCMMN-01
Original Estimation | 4h
Remaining Estimation | 0h

**Comment by estambakio-sc** [comment]
[Demo link](https://opuscapita.github.io/react-crudeditor/branches/issue-277-format/?currentComponentName=ContractEditor&maxContainerWidth=100%25&showSidebar=false)

**Comment by nstoliar-sc** [comment]
Tested for FF, IE and Chrome. Testing was implemented for 'Status' field. It is possible to search items by status. It is possible to edit items status. Please, merge with master branch. Spent 1.5 hours.
