### ISSUE TITLE
Scrollable div appears if Reference Search is the last searchable field

### ISSUE THREAD

**Issue by amogdalov-sc** [OpusCapita/react-crudeditor#287]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01

Implement scrollable div appears if Reference Search is the last searchable field
http://support.jcatalog.com/secure/attachment/141875/Screenshot_4.png

**Comment by nstoliar-sc** [comment]
Tested. Scroll doesn't appear while opening search list if Reference Search is the last field. Please, merge with master branch.
