### ISSUE TITLE
Field errors are not displayed properly

### ISSUE THREAD

**Issue by dkuzmianok-sc** [OpusCapita/react-crudeditor#299]
Meta-Info | Value
-- | --
ExtProjectId | OC-01.1.8
Original Estimation | 4h
Remaining Estimation | 0h

### How to reproduce:
1. open "ContractEditor"
2. press "Create"
3. select any "Status Id"
4. press "Save"

### Expected behaviour
All invalid fields (incl. empty required) should be highlighted.
Can be reproduced [here](https://opuscapita.github.io/react-crudeditor/branches/issue-299/?currentComponentName=ContractEditor&maxContainerWidth=100%25&showSidebar=false)

### Actual behaviour
Only one field is highlighted (description).
Can be reproduced on [master](https://opuscapita.github.io/react-crudeditor/branches/master/?currentComponentName=ContractEditor&maxContainerWidth=100%25&showSidebar=false)

**Comment by nstoliar-sc** [comment]
Tested. Validation messages work correctly. Please, merge with master branch.
