### ISSUE TITLE
Tab key should navigate form grid left-to-right top-to-bottom instead of current top-to-bottom and then left-to-right

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/react-crudeditor#305]
Meta-Info | Value
-- | --
ExtProjectId | OC-01.1.8
Original Estimation | ???h
Remaining Estimation | ???h

https://github.com/OpusCapita/mdm/issues/56#issuecomment-717944265

As a result multi-column navigation with Tab becomes more natural.

**Comment by estambakio-sc** [comment]
How to reproduce current behavior: 
- visit https://opuscapita.github.io/react-crudeditor/branches/master/?currentComponentName=ContractEditor&maxContainerWidth=100%25&showSidebar=false
- click `Edit` on any item
- click on top left field (e.g. focus it)
- press `Tab` key on keyboard
- ---> in scope of section it navigates top-to-bottom in 1st column, then gets to top element on the second column (if it exists) and so on

How to see new behavior: 
- visit https://opuscapita.github.io/react-crudeditor/branches/issue-305/?currentComponentName=ContractEditor&maxContainerWidth=100%25&showSidebar=false
- do the same thing as in previous block
- --> more natural navigation: left-to-right in the first row, then the same on the second row, etc.

Please check in browsers required by eProc (IE11 included).

**Comment by nstoliar-sc** [comment]
Tested. Focus is navigated left-to-right in by each row and then moved to next row. Please, merge with master branch.
