### ISSUE TITLE
Export view name constatns

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/react-crudeditor#36]
According to example in showroom "search", "edit", "create", "view" constants should be defined by developer to use them as conditions in editor schema, f.e.:
```
const VIEW_CREATE = 'create';

const buildFormLayout = viewName => ({ tab, section, field }) => instance => [
  tab({ name: 'general', columns: 2 },
    field({ name: 'glAccountId', readOnly: viewName !== VIEW_CREATE }),
    ....
  )
];
```
View names are internal part of crud representation so it will be more useful to export thees constants as part of crud-editor module.

**Comment by estambakio-sc** [comment]
TBD: should we also expor data types from data-types-lib? @amourzenkov-sc

**Comment by estambakio-sc** [comment]
Implemented in branch `issue-25` in https://github.com/OpusCapita/react-crudeditor/commit/1a64c3a6da47741e45092248ccf93f3486b4c577.
