### ISSUE TITLE
Show/hide Search Form with a button

### ISSUE THREAD

**Issue by amourzenkov-sc** [OpusCapita/react-crudeditor#40]
Implement hideSearchForm flag (see README) like in https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc?utm_source=chrome-app-launcher-info-dialog

**Comment by amourzenkov-sc** [comment]
smth like 
![image](https://user-images.githubusercontent.com/24649844/33210160-1d5bf1f6-d12a-11e7-8634-71b26f777e56.png)

**Comment by estambakio-sc** [comment]
Implemented in #45
