### ISSUE TITLE
React 16 compatibility

### ISSUE THREAD

**Issue by amourzenkov-sc** [OpusCapita/react-crudeditor#42]

**Comment by estambakio-sc** [comment]
@amourzenkov-sc Looks like the error arises for propTypes. We use many @OpusCapita packages which use deprecated React.propTypes instead of standalone 'prop-types' package. I believe the issue is somewhere around propTypes, but we need more investigation.

**Comment by estambakio-sc** [comment]
Bug with reference select is fixed, `showroom` crud demo is compatible with React 16.x

Demo client with navigation is not compatible with React 16.x because it breaks on @opuscapita/react-navigation error. Filed issue: https://github.com/OpusCapita/react-navigation/issues/10
