### ISSUE TITLE
Change CRUD editor view header(s)

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/react-crudeditor#57]
Make editor editor in a way it could be used as breadcrumbs.
E.g. headers for different view would look like this (contract editor example):
- Contracts  -  search view
- [Contracts](#) / New -  create view
- [Contracts](#) / _contract label_ - edit/show view
in last 2 cases link [Contracts](#) serves as [Search result](#) link, see could remove it.
Let's rename (change label) "Create" button with "Add new".

P.S. Similar UI example (Markup) could be seen in term editor [here](http://test.jcatalog.com/demo80/jcdemo/termEditor/terms)

**Comment by amourzenkov-sc** [comment]
If a user wants to go to a View but does not have necessary permissions, display 403 error instead of 500. Adjust error id/message accordingly

**Comment by estambakio-sc** [comment]
Done, closing.
