### ISSUE TITLE
implement RangeInput React Component

### ISSUE THREAD

**Issue by amourzenkov-sc** [OpusCapita/react-crudeditor#86]
"type" property may have the following values:
  * "number",
  * "string",
  * "stringNumber".

**Comment by estambakio-sc** [comment]
Playground: https://opuscapita.github.io/react-crudeditor/branches/range-input/?currentComponentId=%40opuscapita%2Freact-crudeditor%2F0.0.29%2FRangeInput&showSidebar=true

**Comment by estambakio-sc** [comment]
Been tested in #90
